[project]
name = "devops-containers"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Test User", email = "yvesmarinho@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
devops-containers = "devops_containers:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
